分割QRコード でない場合もmeta情報を返却するように修正
QLife-Inc/phonegap-plugin-barcodescanner pull request #2
Opened 2019-10-08 09:26 UTC by noriyq

2019-10-09 00:40 UTC, sonodar commented
#1 にコメントしちゃいました。

2019-10-09 00:56 UTC, sonodar commented
Windows 版にはメタデータがすでにあって、インタフェースが一致していないから取り込まれないかもしれないですね。
https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/qrcode/QRCodeReader.cs

2019-10-09 00:59 UTC, sonodar requested changes
#1 コメントを参照してください

2019-11-14 04:30 UTC, noriyq commented on src/ios/CDVBarcodeScanner.mm
> +    if (format == @"QR_CODE") {
https://github.com/QLife-Inc/phonegap-plugin-barcodescanner/pull/1/files#r332788418
> Java では format が QR_CODE だった場合のみなのに対し、こちらはそうでないのは何か意図がありますか？

ありがとうございます。
修正時期の違いによりブレていただけで特に意図はありません。
こちらもQR_CODEの場合のみに限定しました。

2019-11-15 01:57 UTC, sonodar approved these changes

2019-11-15 01:57 UTC, sonodar commented on src/ios/CDVBarcodeScanner.mm
> +    if (format == @"QR_CODE") {
OK です、ありがとうございます。

2019-11-22 06:31 UTC, merged